[phases.setup]
nixPkgs = ['python39', 'postgresql', 'pip']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'cd backend && pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd backend']

[start]
cmd = 'cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT'
